main:main.o add.o sub.o mul.o div.o main.h
	gcc main.o add.o sub.o mul.o div.o main.h -o main
add.o:add.c
	gcc -c add.c
main.o:main.c
	gcc -c main.c
sub.o:sub.c
	gcc -c sub.c
mul.o:mul.c
	gcc -c mul.c
div.o:div.c
	gcc -c div.c
